name: "Action 1 Consumer"

on:
  pull_request:
  push:

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nipunharjai/custom-github-actions
      with:
        number: 10

